### ISSUE TITLE
Mobs From Spawners Are Not Stacking

### ISSUE THREAD

**Issue by Reese14** [BG-Software-LLC/WildStacker#172]
Server version: CraftBukkit version 2991-Spigot-018b9a0-f3f3094 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
WildStacker version: 3.5.2-DEVb119
Config: https://pastebin.com/k6wjpbNQ

Issue: When a spawner spawns mobs, they are not stacked. If there are 8 spawners placed, and 10 mobs get spawned, they all will be spawned one at a time, and separated instead of stacked.

**Comment by OmerBenGera** [comment]
Does it still happen with latest dev build?

**Comment by Reese14** [comment]
Yes, they are still spawning unstacked.

**Comment by OmerBenGera** [comment]
Take a video of the issue as it seems to work fine for me

**Comment by Reese14** [comment]
https://user-images.githubusercontent.com/68316028/122660227-e33c5100-d14d-11eb-8b9a-b44992a41653.mp4

**Comment by Reese14** [comment]
Do I have to reset the config files or anything after adding the updated plugin version?

**Comment by Distolfix** [comment]
i've the same problem with Blaze. i've the latest version.

**Comment by OmerBenGera** [comment]
Set the stack interval to 200, first of all.
Secondly, try disabling linked entities, let me know if it helps

**Comment by kedavlar** [comment]
i have the same bug and im trying this new config and it work for now

**Comment by Reese14** [comment]
I changed the stack interval and disabled linked entities, still doing the same thing in the video.

**Comment by OmerBenGera** [comment]
> I changed the stack interval and disabled linked entities, still doing the same thing in the video.

Try latest dev build, as I fixed an issue related to that

**Comment by OmerBenGera** [comment]
I will look into that. I fixed a bug related to that, it just needs more tests before I push it.

**Comment by WarnDangerous** [comment]
Hello,

I got the same issue on latest dev build (with "UpgreadableSpawners" mobs do not stack, but it works WELL on WildStacker 3.4.3 !

**Comment by Reese14** [comment]
Okay, I just downloaded the newest version, b147, as well as downloaded WildStackerAPI because I did not have that before, and yeah still no change.

**Comment by OmerBenGera** [comment]
As I said, the fix is not yet released.
Be patient, it will be released soon

**Comment by Reese14** [comment]
Okay, I understand. I was just confused and letting you know lol.

**Comment by OmerBenGera** [comment]
Try b147, it should be better

**Comment by Reese14** [comment]
That's the one I said I was using yesterday.

**Comment by OmerBenGera** [comment]
Weird.
Are you able to replicate the issue on another server with only WS installed?

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue on latest version of Paper and WS, using Iron Golem spawners and your config.

**Comment by OmerBenGera** [comment]
Check out dev build #150, I added support to Paper's PreSpawnSpawnerEvent, so it might help with the issue.

**Comment by WarnDangerous** [comment]
Latest release fixed the issue for me, and now mob spawn is way better, mobs do not take 0.5 seconds until stacking ! :)

**Comment by OmerBenGera** [comment]
> 
> 
> Latest release fixed the issue for me, and now mob spawn is way better, mobs do not take 0.5 seconds until stacking ! :)

Exactly. Instead of waiting for the entity to spawn and then stack it, the plugin will stack it before it spawns (or in other words, when the spawner attempts to spawn it.
One of the disadvantages of this feature is that it doesn't check for entity attributes, and therefore entities that might not be similar can get stacked together (due to restrictions of the event itself). For example, baby horses and big ones will get stacked, etc.

**Comment by Reese14** [comment]
It is still not spawning them correctly. Should I change my server version to Paper instead of CraftBukkit?

**Comment by OmerBenGera** [comment]
> 
> 
> It is still not spawning them correctly on my server, I did not test it on another blank server. Should I change my server version to Paper instead of CraftBukkit?

You're using Spigot, not CraftBukkit, and yes - you should use Paper instead of Spigot if you want this feature.

**Comment by Reese14** [comment]
Switching to Paper solved the issue. Do you know if it will ever work with Spigot?

**Comment by WarnDangerous** [comment]
Spigot is not optimised and shouldn't be used anymore on a server.

Stay on paper will really help you, also maybe dev recommand more and more paper, all plugins work on paper and it offers more performances.

**Comment by OmerBenGera** [comment]
> 
> 
> Switching to Paper solved the issue. Do you know if it will ever work with Spigot?

I don't know what causes that, therefore I can't promise anything.
I couldn't replicate it neither, so I doubt it's gonna be fixed.
I am closing this for now, if it occurs again let me know :)
