### ISSUE TITLE
problem mob count.

### ISSUE THREAD

**Issue by brasilcraft54** [BG-Software-LLC/WildStacker#275]
### Minecraft's Version

purpur-1.17.1 last version

### Plugin's Version

WildStacker-b185

### Describe the bug

there are 50 ghast spawners in the first birth is born 50 more in the others is only born 1 by 1 type went to 51 and then 52 and so it goes 53,54,55,56,57 how do you fix it and it happens with all spawners this.

1° https://www.youtube.com/watch?v=e5bjO_z9VSk

### To Reproduce

put spawners on the ground and let mobs spawn.

**Comment by OmerBenGera** [comment]
Send me your config please

**Comment by brasilcraft54** [comment]
how to make the mobs that are born by mobspawner not have AI


https://pastebin.com/0bP1nry0

**Comment by OmerBenGera** [comment]
I will look into that.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build

**Comment by WarnDangerous** [comment]
Hello,

latested dev build (b191) didn't fix my issue (#278), mobs still increase 1 by 1 but it spawned another cow (x1)
![Screenshot_5724](https://user-images.githubusercontent.com/31826333/130236327-162b3226-d2ef-4315-95d0-bf72a51ed25b.png)

**Comment by WarnDangerous** [comment]
Upgradeablespawner is a bit different, you don't get "x2 or x3" spawners, it's a vanilla spawner but that can be faster.

and a vanilla spawner can spawn up to 4 mobs, but with listen-paper-pre-spawn-event: true it will only spawn 1 mob by 1 mob on the stacked mob count.

**Comment by OmerBenGera** [comment]
> 
> 
> Upgradeablespawner is a bit different, you don't get "x2 or x3" spawners, it's a vanilla spawner but that can be faster.
> 
> and a vanilla spawner can spawn up to 4 mobs, but with listen-paper-pre-spawn-event: true it will only spawn 1 mob by 1 mob on the stacked mob count.

If it works without UpgradableSpawner, then it works as intended.
I don't know what UpgradableSpawner is, and it might conflict with WildStacker.

**Comment by WarnDangerous** [comment]
> > Upgradeablespawner is a bit different, you don't get "x2 or x3" spawners, it's a vanilla spawner but that can be faster.
> > and a vanilla spawner can spawn up to 4 mobs, but with listen-paper-pre-spawn-event: true it will only spawn 1 mob by 1 mob on the stacked mob count.
> 
> If it works without UpgradableSpawner, then it works as intended.
> I don't know what UpgradableSpawner is, and it might conflict with WildStacker.

It works only with  listen-paper-pre-spawn-event: FALSE, as explained on my other ticket.
It's two different issues.

Upgradeablespawners is a spawner provider that allows player to make spawner faster (but not stack them like spawner x2, x3 etc.)

**Comment by OmerBenGera** [comment]
> 
> 
> > > Upgradeablespawner is a bit different, you don't get "x2 or x3" spawners, it's a vanilla spawner but that can be faster.
> > > and a vanilla spawner can spawn up to 4 mobs, but with listen-paper-pre-spawn-event: true it will only spawn 1 mob by 1 mob on the stacked mob count.
> > 
> > 
> > If it works without UpgradableSpawner, then it works as intended.
> > I don't know what UpgradableSpawner is, and it might conflict with WildStacker.
> 
> It works only with listen-paper-pre-spawn-event: FALSE, as explained on my other ticket.
> It's two different issues.
> 
> Upgradeablespawners is a spawner provider that allows player to make spawner faster (but not stack them like spawner x2, x3 etc.)

Again, check it without Upgradeablespawners, let me know if it still occurs or not.

**Comment by WarnDangerous** [comment]
> > > > Upgradeablespawner is a bit different, you don't get "x2 or x3" spawners, it's a vanilla spawner but that can be faster.
> > > > and a vanilla spawner can spawn up to 4 mobs, but with listen-paper-pre-spawn-event: true it will only spawn 1 mob by 1 mob on the stacked mob count.
> > > 
> > > 
> > > If it works without UpgradableSpawner, then it works as intended.
> > > I don't know what UpgradableSpawner is, and it might conflict with WildStacker.
> > 
> > 
> > It works only with listen-paper-pre-spawn-event: FALSE, as explained on my other ticket.
> > It's two different issues.
> > Upgradeablespawners is a spawner provider that allows player to make spawner faster (but not stack them like spawner x2, x3 etc.)
> 
> Again, check it without Upgradeablespawners, let me know if it still occurs or not.

yes it does

**Comment by OmerBenGera** [comment]
I will check it again.

**Comment by OmerBenGera** [comment]
@WarnDangerous Send me your config file, as it works fine for me.

**Comment by WarnDangerous** [comment]
https://pastebin.com/EKAAefsb

i'll try on paper 1.16.5 without any plugin except wildstacker and try to reproduce

**Comment by OmerBenGera** [comment]
> 
> 
> https://pastebin.com/EKAAefsb
> 
> i'll try on paper 1.16.5 without any plugin except wildstacker and try to reproduce

I understand the issue now - because you have stacked spawners disabled, you get only 1mob spawned instead of 1-4.
I will look into that as well, even tho it's not the same issue described in the issue above.

**Comment by WarnDangerous** [comment]
> > https://pastebin.com/EKAAefsb
> > i'll try on paper 1.16.5 without any plugin except wildstacker and try to reproduce
> 
> I understand the issue now - because you have stacked spawners disabled, you get only 1mob spawned instead of 1-4.
> I will look into that as well, even tho it's not the same issue described in the issue above.

That's why I opened a different ticket, we misunderstood on the issue
But yeah my issue is exactly that :)

**Comment by OmerBenGera** [comment]
> 
> 
> > > https://pastebin.com/EKAAefsb
> > > i'll try on paper 1.16.5 without any plugin except wildstacker and try to reproduce
> > 
> > 
> > I understand the issue now - because you have stacked spawners disabled, you get only 1mob spawned instead of 1-4.
> > I will look into that as well, even tho it's not the same issue described in the issue above.
> 
> That's why I opened a different ticket, we misunderstood on the issue
> But yeah my issue is exactly that :)

My bad. I am closing this one and re-opening the other one.

**Comment by brasilcraft54** [comment]
sorry to reopen this ticket but you have a problem with the ghast of 50 mobspawner is born 50 and then over 1k and the maximum was supposed to be 200 and not over 1k.

**Comment by OmerBenGera** [comment]
> 
> 
> sorry to reopen this ticket but you have a problem with the ghast of 50 mobspawner is born 50 and then over 1k and the maximum was supposed to be 200 and not over 1k.

Open a new issue regarding this
