### ISSUE TITLE
InstantKill problem

### ISSUE THREAD

**Issue by Askarionn** [BG-Software-LLC/WildStacker#346]
### Minecraft's Version

Airplane 1.16.5

### Plugin's Version

2.1.7 devbuild

### Describe the bug

I disabled the instantkill feature but mobs are still killed instantly

### To Reproduce

# Instant-kill will kill the entire stack instead of unstack it by one.
  # When an entire stack dies, their drops are getting multiplied.
  # EntityType list: https://bg-software.com/entities/
  # DamageCause list:  https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
  # You can combine both filters using "ENTITY_TYPE:DAMAGE_CAUSE" or "ENTITY_TYPE:SPAWN_REASON"
  # If you don't want instant-kill, use "instant-kill: []"
  instant-kill: []

**Comment by OmerBenGera** [comment]
Take a video of the issue.
instant-kill is used to kill an entire stack of mobs at once, instead of killing only one mob in the stack.
If it occurs, test using the inspect tool that the mob actually had a stack size.

**Comment by Askarionn** [comment]
I'm pretty sure that is a problem related to WildStacker, i saw other people reporting this problem on discord, i have friends that have the same problem. It's happening with newer versions of wildstacker. After i update to latest 2.1.7 build the problem appeard.

**Comment by Askarionn** [comment]
It happens with more players online not with just 1

**Comment by OmerBenGera** [comment]
> It happens with more players online not with just 1

I dont see how it is related to the amount of players online, however I will look into that.

**Comment by OmerBenGera** [comment]
Check out latest build, I fixed some things related to weird behaviors of mobs, it might fix your issue as well.

**Comment by Askarionn** [comment]
I tried 3.6.1 and it's still happening.
For example if i'm the only player online or with other 2-3 players it doesn't happen.

**Comment by Askarionn** [comment]
I tested with 3.6.0 devbuild 1.4.1 it's working good

**Comment by OmerBenGera** [comment]
> I tested with 3.6.0 devbuild 1.4.1 it's working good

Is this the latest build that works fine?
If not, find the latest one so I can check what was changed in that version

**Comment by OmerBenGera** [comment]
Mind checking out latest build?
I fixed some potential issues with removing entities, may fix this issue.

(As you probably guessed, I am not sure what causing the issue, so by fixing other issues I hope this issue will be fixed as well)

**Comment by OmerBenGera** [comment]
Have you tried it?

**Comment by Askarionn** [comment]
Hello! I didn't test it yet, i will test it these days and i'm gonna announce you

**Comment by Innesity** [comment]
> Have you tried it?

The issue has been resolved. I also talked with Askarion on discord and can confirm the issue is fixed on his network too.

Thanks for support!

**Comment by OmerBenGera** [comment]
I am glad to hear that :)
