### ISSUE TITLE
Stacked spawners acting like 1 spawner

### ISSUE THREAD

**Issue by NotToBlame** [BG-Software-LLC/WildStacker#38]
Some spawners that are stacked, for example, to 500. Still act like one ordinary spawner. It's not consistent as to when they act normal or behave this way

Server Version: Paper 1.16.5 #457
Plugin version: b59
Java version: Java 11 OpenJDK 64-Bit Server VM 11.0.9.1+1
Config File: https://pastebin.com/MsDSdK07

**Comment by OmerBenGera** [comment]
I need to know your java version.

**Comment by NotToBlame** [comment]
Hey, I've found where to find the Java version however it's not specific. With our host it has a config for what one to use and it's using Java 11. If you need a specific version then let me know I'll see what I can find

**Comment by OmerBenGera** [comment]
Do you know how to replicate the issue on a server with only WS installed?

**Comment by NotToBlame** [comment]
I will attempt to but it seems temperamental when spawners want to act normally and act like one spawner. Normally breaking the whole stack and placing a whole stack back will fix this issue

**Comment by NotToBlame** [comment]
So far the only thing I could find was that one of the spawners that is usually broken on the main server was only 1 normal spawner when loading up the test server. I couldn't replicate this with 500 since when making the stack, it fixes the issue

**Comment by OmerBenGera** [comment]
You'll have to find what causes it

**Comment by Lambsy** [comment]
It is fixed for us when we restart the server. Is it possible to expand reload command somehow to restart spawners or something in that nature as they appear to work properly when server is restarted.

**Comment by OmerBenGera** [comment]
> 
> 
> It is fixed for us when we restart the server. Is it possible to expand reload command somehow to restart spawners or something in that nature as they appear to work properly when server is restarted.

Instead of adding weird features, the issue should be fixed without weird reload spawners systems.

**Comment by Lambsy** [comment]
> > It is fixed for us when we restart the server. Is it possible to expand reload command somehow to restart spawners or something in that nature as they appear to work properly when server is restarted.
> 
> Instead of adding weird features, the issue should be fixed without weird reload spawners systems.

Understandable but we've already spent quite some time trying to replicate it with no success so could work as a temporary band aid solution as you've said we must find what causes it with no more information so that may take a while if it is ever found why as it seems so far to be quite random.

**Comment by OmerBenGera** [comment]
> 
> 
> > > It is fixed for us when we restart the server. Is it possible to expand reload command somehow to restart spawners or something in that nature as they appear to work properly when server is restarted.
> > 
> > 
> > Instead of adding weird features, the issue should be fixed without weird reload spawners systems.
> 
> Understandable but we've already spent quite some time trying to replicate it with no success so could work as a temporary band aid solution as you've said we must find what causes it with no more information so that may take a while if it is ever found why as it seems so far to be quite random.

The only solution will be when we find what causes it and then it will be fixed.
You reported it for the first time yesterday, so you should be patient until a solution is found.

**Comment by DatblockCom** [comment]
Any clues what might be causing it? Like are there certain conditions that must be met that somehow may not be met caused by something else such a server setting?

**Comment by Lambsy** [comment]
Not sure if this can help but it also loses the condition settings for when to spawn a mob. For example we disabled all necessary conditions for mobs to spawn but then the mob spawners get bugged they require the vanilla set conditions for spawning a mob. So it seems that the spawner fully reverts to a vanilla spawner though it still detects that the stacked mob spawners is at the location when using the tool to check it.

**Comment by OmerBenGera** [comment]
It sounds like the spawner is overridden by another source causing WildStacker's methods to not work.
Are you able to replicate it on a server with only WS installed?

**Comment by Lambsy** [comment]
I am not able to replicate it with only WS, nor have I been able to replicate it with seemingly the same setup on a second server to replicate the issue so I really have no clue any longer. On the real server itself, it only happens for some spawners, not sure if its related to the age of the spawner or what it could be. I ported the WildStacker database, and all the other plugins I had, and the region files where spawners that would get bugged by leaving the chunk and coming back, and tried to replicate it on that second server, but no luck as I said, they still spawn correctly when returning. 

Using a plugin like ServerUtils, and running /servutils reloadplugin WildStacker, makes the bugged spawners, start spawning correctly again. 

I'm not sure what to really try now in order to try and find the root of the issue. It would be appreciated if some sort of optional failsafe could be added though I understand if that route is not preferred.

**Comment by OmerBenGera** [comment]
Hmm weird. It should fix itself everytime you unload the chunk and then load it again, however it shouldn't occur at the first place.
I'll try to look into that on my end, check what might cause it. Anyways, I am closing the issue :)

**Comment by Lambsy** [comment]
This issue is sort of game breaking for our server and unloading and loading the chunk doesn't fix it, that's what causes the issues for some spawners. Why is the issue being closed when it hasn't been resolved, I'm confused.

**Comment by OmerBenGera** [comment]
> 
> 
> This issue is sort of game breaking for our server and unloading and loading the chunk doesn't fix it, that's what causes the issues for some spawners. Why is the issue being closed when it hasn't been resolved, I'm confused.

You said you can't replicate the issue...

**Comment by OmerBenGera** [comment]
Also, unloading and loading the chunk will 100% fix it. If not, then another plugin is probably breaking it.

**Comment by Lambsy** [comment]
Here's a video comparing two different spawner rooms, one spawning and one not spawning them: https://cdn.discordapp.com/attachments/736160684605308960/817014169210847262/wot.mov

Perhaps could relook how the loading of the spawners is done? It is hard to find any way to replicate it as it is seemingly happening randomly.

**Comment by OmerBenGera** [comment]
Spawners are loaded every time a chunk is loaded, nothing special.
You probably have another plugin or something overriding the MobSpawnerAbstract class as well, causing it to override WildStacker too. If it's not a plugin, might be something with your spigot jar.
Also, from your video, you show two rooms, one of them is working but spawners spawn only 1 mob, and in the other room mobs aren't spawning at all, so this video doesn't show really anything. Also, there's no need to use /ws stats, it will not tell anything regarding the issue

**Comment by OmerBenGera** [comment]
I pushed an update (build 77), check if it helps

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Lambsy** [comment]
Sorry for late response. I tried the new build but I believe it was still occurring. I haven't had the chance to look into it for a while. It most likely is some sort of plugin compatibility if no one else is occurring this so may best to close the issue.

**Comment by OmerBenGera** [comment]
@Lambsy I am not gonna close it, we'll have to find the compatibility issue if it even exists.
Have you managed to get it working with only WildStacker installed?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by LeRoiDamien** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
> 
> 
> Any news regarding this?

No as no one have yet to find the cause of the issue or how to replicate it.

**Comment by LeRoiDamien** [comment]
So when I unload the chunk then I go back to the chunk the spawner works correctly 2-3 minutes later the spawners are back in 1 by 1

**Comment by OmerBenGera** [comment]
> 
> 
> So when I unload the chunk then I go back to the chunk the spawner works correctly 2-3 minutes later the spawners are back in 1 by 1

Yeah that doesn't help with anything. Let me know how tor replicate it, also make sure you check it with the inspect tool.

**Comment by LeRoiDamien** [comment]
So for my part I just found the problem I put

whitelist:
    - ZOMBIFIED_PIGLIN:SPAWNER
    - ZOMBIE:SPAWNER
    - WITCH:SPAWNER
    - WITHER_SKELETON:SPAWNER
    and now 
    
    whitelist: []
    
    so now for the moment the spawn is correct

**Comment by LeRoiDamien** [comment]
hello, well not always the same for the spawn: /

**Comment by OmerBenGera** [comment]
> 
> 
> So for my part I just found the problem I put
> 
> whitelist:
> - ZOMBIFIED_PIGLIN:SPAWNER
> - ZOMBIE:SPAWNER
> - WITCH:SPAWNER
> - WITHER_SKELETON:SPAWNER
> 
> ```
> and now 
> 
> whitelist: []
> 
> so now for the moment the spawn is correct
> ```

If you make only specific entities to be whitelisted, it occurs?
Does it occur with the spawners of these entity types, or only with others, or both?

**Comment by LeRoiDamien** [comment]
Hi, no no, I have the problem again :/

**Comment by LeRoiDamien** [comment]
I didn't try without the ": spawner"
Then with all the entities

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by LeRoiDamien** [comment]
Seems like it's good for me

**Comment by OmerBenGera** [comment]
Great :)
