### ISSUE TITLE
Mobs are invinsibl after killing one due to error related to experience orbs 

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildStacker#473]
### Minecraft's Version

1.18.1 Purpur 1566

### Plugin's Version

dev 290

### Describe the bug

When wildstacker is installed it causes all dropped EXP to be registered as CUSTOM reason.

### To Reproduce

Install Wildstacker, check exp orb pickup spawn reason.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build

**Comment by Skizzles** [comment]
@OmerBenGera this issue has returned in ur current dev builds.

**Comment by Skizzles** [comment]
Tested with just wildstacker installed, 1.19.2 purpur dev 1776, wildstacker dev 349

**Comment by OmerBenGera** [comment]
This is fixed in latest dev build

**Comment by Skizzles** [comment]
@OmerBenGera doesnt this fix need to be applied to 1.18, 1.19 etc. You only added the commit to 1.17 NMS adapter and not the others. My testing shows this issue still is present in my 1.19.2 environment.

**Comment by OmerBenGera** [comment]
> @OmerBenGera doesnt this fix need to be applied to 1.18, 1.19 etc. You only added the commit to 1.17 NMS adapter and not the others. My testing shows this issue still is present in my 1.19.2 environment.

When I converted all the obfuscated nms to mojang-mappings one, I also fixed this for all versions above 1.17.
There wasn't a specific commit for the fix, I know, but it should be fixed.

**Comment by Skizzles** [comment]
> > @OmerBenGera doesnt this fix need to be applied to 1.18, 1.19 etc. You only added the commit to 1.17 NMS adapter and not the others. My testing shows this issue still is present in my 1.19.2 environment.
> 
> When I converted all the obfuscated nms to mojang-mappings one, I also fixed this for all versions above 1.17. There wasn't a specific commit for the fix, I know, but it should be fixed. My bad on that, I will make sure next time they are in separate commits.

oh no its fine I was just trying to find it as I was still experiencing the issue. This shows exp output is custom.
https://screenshots.skizzles.me/wAnA3/qepAJOwU60.mp4

**Comment by OmerBenGera** [comment]
> > > @OmerBenGera doesnt this fix need to be applied to 1.18, 1.19 etc. You only added the commit to 1.17 NMS adapter and not the others. My testing shows this issue still is present in my 1.19.2 environment.
> > 
> > 
> > When I converted all the obfuscated nms to mojang-mappings one, I also fixed this for all versions above 1.17. There wasn't a specific commit for the fix, I know, but it should be fixed. My bad on that, I will make sure next time they are in separate commits.
> 
> oh no its fine I was just trying to find it as I was still experiencing the issue. This shows exp output is custom. https://screenshots.skizzles.me/wAnA3/qepAJOwU60.mp4

It still occurs?

**Comment by Skizzles** [comment]
> > > > @OmerBenGera doesnt this fix need to be applied to 1.18, 1.19 etc. You only added the commit to 1.17 NMS adapter and not the others. My testing shows this issue still is present in my 1.19.2 environment.
> > > 
> > > 
> > > When I converted all the obfuscated nms to mojang-mappings one, I also fixed this for all versions above 1.17. There wasn't a specific commit for the fix, I know, but it should be fixed. My bad on that, I will make sure next time they are in separate commits.
> > 
> > 
> > oh no its fine I was just trying to find it as I was still experiencing the issue. This shows exp output is custom. https://screenshots.skizzles.me/wAnA3/qepAJOwU60.mp4
> 
> Does it still occur?

yes

**Comment by OmerBenGera** [comment]
> > > > > @OmerBenGera doesnt this fix need to be applied to 1.18, 1.19 etc. You only added the commit to 1.17 NMS adapter and not the others. My testing shows this issue still is present in my 1.19.2 environment.
> > > > 
> > > > 
> > > > When I converted all the obfuscated nms to mojang-mappings one, I also fixed this for all versions above 1.17. There wasn't a specific commit for the fix, I know, but it should be fixed. My bad on that, I will make sure next time they are in separate commits.
> > > 
> > > 
> > > oh no its fine I was just trying to find it as I was still experiencing the issue. This shows exp output is custom. https://screenshots.skizzles.me/wAnA3/qepAJOwU60.mp4
> > 
> > 
> > Does it still occur?
> 
> yes

How do you check for the spawn reason of the orb?
Show me the code that prints it out.

**Comment by OmerBenGera** [comment]
Check out latest dev build, hopefully it will work now

**Comment by Skizzles** [comment]
> Check out latest dev build, hopefully it will work now

ENTITY_DEATH is now working properly. Just a single warning thrown here:
[18:54:46 WARN]: [WildStacker] Task #5314 for WildStacker v3.8.1.358 generated an exception
java.lang.IllegalArgumentException: The entity-type EXPERIENCE_ORB is not a stackable entity.
        at com.bgsoftware.wildstacker.objects.WStackedEntity.of(WStackedEntity.java:76) ~[WildStacker-3.8.1-b358.jar:?]
        at com.bgsoftware.wildstacker.nms.v1192.NMSAdapter.createEntity(NMSAdapter.java:190) ~[WildStacker-3.8.1-b358.jar:?]
        at com.bgsoftware.wildstacker.nms.v1192.NMSAdapter.spawnExpOrb(NMSAdapter.java:202) ~[WildStacker-3.8.1-b358.jar:?]
        at com.bgsoftware.wildstacker.utils.entity.EntityUtils.spawnExp(EntityUtils.java:152) ~[WildStacker-3.8.1-b358.jar:?]
        at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$null$3(DeathSimulation.java:209) ~[WildStacker-3.8.1-b358.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1774]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1774]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1520) ~[purpur-1.19.2.jar:git-Purpur-1774]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1774]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1444) ~[purpur-1.19.2.jar:git-Purpur-1774]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[purpur-1.19.2.jar:git-Purpur-1774]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1774]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        
Side note, when the entity is stacked it causes the stack to become invincible after this warn is thrown. Unsure if related.

**Comment by ItzFabb-uwu** [comment]
BUMP This issue is occured on 1.8.8

**Comment by ItzFabb-uwu** [comment]
So Omer_R is there anything i can do or i have to wait until it's patched on the next dev builds?

**Comment by Skizzles** [comment]
> So Omer_R is there anything i can do or i have to wait until it's patched on the next dev builds?

Wait till its fixed or revert to an older build.

**Comment by Rhys00** [comment]
When is this being fixed its been a couple days now. Surely a fix soon?

**Comment by OmerBenGera** [comment]
> When is this being fixed its been a couple days now. Surely a fix soon?

I only work on weekends.
Meanwhile downgrade.

**Comment by OmerBenGera** [comment]
@Skizzles @ItzFabb-uwu @Rhys00 Fixed in latest dev build

**Comment by WarnDa** [comment]
Fixed for me, thanks ! (I'm using 1.19.2)

**Comment by OmerBenGera** [comment]
Great, closing this for now.
@Skizzles if there are new issues, make sure you open a new issue regarding them.
